import React, {useEffect, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowLeft, ArrowRight, Check, SlidersHorizontal, Target} from 'lucide-react';
import './styles.css';
import {DEFAULT_CONFIG,FIXTURES,decodeSave,emptyEntry,expectedGoals,matchResult,name,probabilities,standings,teamSlot,validateConfig} from './game.js';

const KEY='throwball-mw1-v3';
const LEGACY_KEY='throwball-mw1-v2';
function App(){
 const [selected,setSelected]=useState(0),[entries,setEntries]=useState({}),[drafts,setDrafts]=useState({}),[config,setConfig]=useState(DEFAULT_CONFIG),[tuning,setTuning]=useState(DEFAULT_CONFIG),[ready,setReady]=useState(false),[message,setMessage]=useState('Progress saves automatically on this device.'),[error,setError]=useState('');
 useEffect(()=>{try{const raw=localStorage.getItem(KEY)||localStorage.getItem(LEGACY_KEY); if(raw){const parsed=JSON.parse(raw),s=decodeSave(raw); setEntries(s.entries); setDrafts(s.drafts); setConfig(s.config); setTuning(s.config); if(Number.isInteger(parsed.selected)&&parsed.selected>=0&&parsed.selected<FIXTURES.length)setSelected(parsed.selected); setMessage('Saved progress restored.');}}catch{setError('Your saved game could not be loaded. This session starts fresh.');} setReady(true);},[]);
 useEffect(()=>{if(!ready)return; const payload=JSON.stringify({entries,drafts,config,selected,savedAt:new Date().toISOString()}); localStorage.setItem(KEY,payload); localStorage.removeItem(LEGACY_KEY);},[ready,entries,drafts,config,selected]);
 const fixture=FIXTURES[selected],entry=drafts[fixture.id]??entries[fixture.id]??emptyEntry(),saved=entries[fixture.id],result=saved?matchResult(fixture,saved,config):null,dirty=!!saved&&JSON.stringify(entry)!==JSON.stringify(saved),rows=standings(entries,config),played=Object.keys(entries).length;
 const nav=i=>{setSelected(i);setMessage('Progress saved automatically.');setError('');};
 const update=(side,i,value)=>{setDrafts(d=>({...d,[fixture.id]:{...entry,[side]:entry[side].map((v,n)=>n===i?value:v)}}));setError('');setMessage('Unfinished darts saved automatically.');};
 const record=()=>{try{const r=matchResult(fixture,entry,config),e={home:r.home.throws,away:r.away.throws};setEntries(s=>({...s,[fixture.id]:e}));setDrafts(s=>({...s,[fixture.id]:e}));setMessage(`${name(fixture.home)} ${r.home.goals}-${r.away.goals} ${name(fixture.away)} recorded and saved.`);setError('');}catch(e){setError(e.message);setMessage('');}};
 const apply=ev=>{ev.preventDefault();try{validateConfig(tuning);setConfig(structuredClone(tuning));setMessage('Model applied and saved. Recorded results have been recalculated.');setError('');}catch(e){setError(e.message);}};
 return <main>
  <header className="top"><div className="brand"><Target/>THROW<span>BALL</span></div><div>Premier League 26/27</div><div>First round</div></header>
  <section className="intro"><div><p>The dartboard decides</p><h1>Matchweek one.</h1><span>Three darts per team. Ten fixtures. One opening table.</span></div><strong>{played}<small>/10</small></strong></section>
  <div className="workspace"><aside className="fixtures"><h2>Fixtures</h2>{FIXTURES.map((f,i)=>{const r=entries[f.id]?matchResult(f,entries[f.id],config):null;return <button className={i===selected?'active':''} key={f.id} onClick={()=>nav(i)}><b>{String(i+1).padStart(2,'0')}</b><span>{name(f.home)}<br/>{name(f.away)}</span><strong>{r?`${r.home.goals}:${r.away.goals}`:'-'}</strong></button>})}</aside>
  <section className="play"><div className="board"><div className="meta"><span>Match {selected+1}/10</span><span>{fixture.date}</span><span>{result?'Recorded':'Ready'}</span></div><div className="score"><Team id={fixture.home} home config={config}/><div className="numbers">{result?result.home.goals:'-'}<span>:</span>{result?result.away.goals:'-'}</div><Team id={fixture.away} config={config}/></div><p>{dirty?'Unrecorded changes. Scoreboard shows the saved result.':result?'Full time.':'Enter both visits to reveal the score.'}</p></div>
  <form className="entry" onSubmit={e=>{e.preventDefault();record();}}>{['home','away'].map(side=>{const id=fixture[side],slot=teamSlot(id),r=result?.[side];return <fieldset key={side}><legend><span>{id}</span>{name(id)}<b>Target {slot}</b></legend><div className="darts">{entry[side].map((v,i)=><label key={i}>Dart {i+1}<input aria-label={`${name(id)} dart ${i+1}`} value={v} placeholder={['5','D8','17'][i]} onChange={e=>update(side,i,e.target.value)} /></label>)}</div>{r&&<p className="combo">{saved[side].join(' | ')}<br/>ID {r.id.toLocaleString('en-GB')} | {(r.percentile*100).toFixed(3)}% | {r.boostHits} boost hit{r.boostHits===1?'':'s'}</p>}</fieldset>})}<div className="actions"><span>Order matters. Singles, doubles and trebles on the target number all boost.</span><button>{result?'Update result':'Reveal & record'}<ArrowRight size={18}/></button></div></form>
  <p className={error?'feedback error':'feedback'}>{error||message}</p><nav className="matchnav"><button disabled={selected===0} onClick={()=>nav(selected-1)}><ArrowLeft size={16}/> Previous</button><button disabled={selected===9} onClick={()=>nav(selected+1)}>Next <ArrowRight size={16}/></button></nav>
  <details className="model"><summary><SlidersHorizontal size={18}/> Match probabilities and settings</summary><div className="probgrid">{['home','away'].map(side=>{const id=fixture[side],other=fixture[side==='home'?'away':'home'],hits=result?.[side].boostHits??0,lambda=expectedGoals(id,other,side==='home',config,hits);return <section key={side}><h3>{name(id)}</h3><p>Target {teamSlot(id)} | boosts {hits} | rate {lambda.toFixed(2)}</p>{probabilities(lambda).map((p,g)=><div className="bar" key={g}><span>{g}</span><i><b style={{width:`${p*100}%`}} /></i><span>{(p*100).toFixed(1)}%</span></div>)}</section>})}</div><form onSubmit={apply} className="settings">{[['baseGoals','Base rate',0.3,3,0.05],['homeAdvantage','Home',1,2,0.01],['strengthScale','Scale',10,100,1],['slotBoost','Slot boost',0,0.5,0.01]].map(([key,label,min,max,step])=><label key={key}>{label}<input type="number" min={min} max={max} step={step} value={Number.isNaN(tuning[key])?'':tuning[key]} onChange={e=>setTuning(c=>({...c,[key]:e.target.valueAsNumber}))}/></label>)}<button><Check size={16}/> Apply</button></form></details>
  </section></div>
  <section className="table"><h2>Your table</h2><table><thead><tr>{['#','Club','P','W','D','L','GF','GA','GD','Pts'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id}><td>{i+1}</td><td>{r.club}</td><td>{r.p}</td><td>{r.w}</td><td>{r.d}</td><td>{r.l}</td><td>{r.gf}</td><td>{r.ga}</td><td>{r.gd}</td><td><b>{r.pts}</b></td></tr>)}</tbody></table></section>
 </main>;
}
function Team({id,home,config}){return <div><span>{home?'HOME':'AWAY'}</span><h2>{name(id)}</h2><p>Strength {config.ratings[id]} | Target {teamSlot(id)}</p></div>}

createRoot(document.getElementById('root')).render(<App/>);
